from enum import Enum

#Assistant Enum classes to limit the bounds of what states and games can be.
class RoomStates(Enum):
    WAITING = "Waiting"
    PLAYING = "Playing"

class Games(Enum):
    NOT_SELECTED = "Not selected"
    SLANG = "Slang"
    CRASH = "Crash Out"

class GameRoom:
    def __init__(self, room_code):
        """Room code is generated by the room manager and passed to each room on init.
        Players: an array of player names.
        State: The current state of the room {Waiting, Playing}. Rooms cannot be joined when playing
        Host: The leader/admin of the room
        Game: The current game selected to be played. Required for routing game calls to their appropriate logic."""
        self.room_code = room_code
        self.players = []
        self.state = "waiting"
        self.host = ""
        self.game = Games.NOT_SELECTED

    def add_player(self, player_name):
        if player_name not in self.players:
            if len(self.players) == 0:
                self.host = player_name
            self.players.append(player_name)
            return "Success"
        else:
            return "Error"
    def remove_player(self, player_name):
        if player_name in self.players:
            self.players.remove(player_name)
            return "Success"
        else:
            return "Error"

    def start_game(self):
        self.state = RoomStates.PLAYING
        if len(self.players) >= 2:
            print("Success starting the game")
            return "Success"
        else:
            return "Error"
    def end_game(self):
        self.state = RoomStates.WAITING

    def set_game(self, game_id):
        #game == <game_id>
        if game_id == "Slang":
            self.game = Games.SLANG
        elif game_id == "Crash out":
            self.game = Games.CRASH

    def handle_action(self, action_type, payload):