from enum import Enum
from typing import Dict, Any

from backend.Games.Game2.GameEngine.CrashOutEngine import CrashOutEngine
#Assistant Enum classes to limit the bounds of what states and games can be.
class RoomStates(Enum):
    EMPTY = "Empty"
    WAITING = "Waiting"
    PLAYING = "Playing"

class Games(Enum):
    NOT_SELECTED = "Not selected"
    SLANG = "Slang"
    CRASH = "Crash Out"

class GameRoom:
    def __init__(self, room_code, sio):
        """Room code is generated by the room manager and passed to each room on init.
        Players: an array of player names.
        State: The current state of the room {Waiting, Playing}. Rooms cannot be joined when playing
        Host: The leader/admin of the room
        Game: The current game selected to be played. Required for routing game calls to their appropriate logic."""
        self.room_code = room_code
        self.sio = sio
        self.players = []
        self.state = "waiting"
        self.host = ""
        self.game = Games.NOT_SELECTED
        self.active_engine = None

    def check_for_player(self, player_name):
        if player_name not in self.players:
            return "Error"
        else:
            return "Success"

    def add_player(self, player_name):
        if player_name not in self.players:
            if len(self.players) == 0:
                self.host = player_name
            self.players.append(player_name)
            return "Success"
        else:
            return "Error"
    def remove_player(self, player_name):
        print("Removing Player: ", player_name)
        if player_name in self.players:
            self.players.remove(player_name)
            if len(self.players) == 0:
                self.state = RoomStates.EMPTY
            print("Remaining Players: ", self.players)
            return "Success"
        else:
            return "Error"

    async def start_game(self): #should be dynamic depending on the game, for now assuming crash out
        self.state = RoomStates.PLAYING
        if len(self.players) >= CrashOutEngine.MINIMUM_PLAYERS:
            self.active_engine = CrashOutEngine(players=self.players, sio=self.sio, room=self.room_code)
            await self.active_engine.start() #Start the game loop
            return "Success"
        else:
            return "Error"
    def end_game(self):
        self.state = RoomStates.WAITING

    def set_game(self, game_id):
        #game == <game_id>
        if game_id == "Slang":
            self.game = Games.SLANG
        elif game_id == "Crash Out":
            self.game = Games.CRASH
        return self.game
    async def handle_event(self, username:str, event_type:str, data:Dict[str, Any]):
        if self.active_engine is not None:
            status, message, local_data, broadcast_data = await self.active_engine.handle_event(username, event_type, data)
            return status, message, local_data, broadcast_data
        else:
            return False,"No active engine found for this room.", None